openapi: 3.0.3
info:
  title: Customer App API Design
  description: first draft of app API design
  version: 1.0.1
paths:
  /order/create:
    post:
      summary: notifying system server of creation of new order
      requestBody: 
        content:
          application/json:
            schema:
              type: object
              properties:
                recipientId:
                  type: string
                  description: id of customer
                  example: recipient1
                storeAddress:
                  type: integer
                  description: postal code of store 
                  example: 486038
                recipientAddress:
                  type: integer
                  description: postal code of customer address
                  example: 487372
                itemDescription:
                  type: string
                  example: random parcel from ccp
      responses:
        200:
          description: success response
          content:
            application/json:
              schema:
                type: object
                properties:
                  orderId:
                    type: integer
                    example: 3123
                  storeId:
                    type: string
                    description: id of store or person dispatching the order
                    example: store1
                  recipientId:
                    type: string
                    description: id of customer
                    example: recipient1
                  storeAddress:
                    type: integer
                    description: postal code of store 
                    example: 486038
                  recipientAddress:
                    type: integer
                    description: postal code of customer address
                    example: 487372
                  itemDescription:
                    type: string
                    example: random parcel from ccp
  /order/{id}:
    parameters:
      - in: path
        name: id
        required: true
        schema:
          type: integer
    delete:
      summary:  notifying system server of deletion of by order id
      responses:
        200:
          description: success resonponse
        
  /order/{id}/status:
    parameters:
      - in: path
        name: id
        required: true
        schema:
          type: integer
    get:
      summary: get order status from system server
      responses:
        200:
          description: success response
          content:
            application/json:
              schema:
                type: object
                properties:
                  orderId:
                    type: integer
                    example: 1
                  status:
                    type: string
                    enum:
                      - order received
                      - robot dispatched
                      - on the way
                      - at hub
                      - delivered
                      - cancelled
                      - failed
    
  /order/{id}/robotId:
    parameters:
      - in: path
        name: id
        required: true
        schema:
          type: integer
    get:
      summary: get robot id from system server
      responses:
        200:
          description: success response
          content:
            application/json:
              schema:
                type: object
                properties:
                  robotId: 
                    type: integer
                    description: robot assigned for delivery
                    example: 1234
