openapi: 3.0.0
servers:
  # Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/capstone_s13/system_server_api/1.0.0
info:
  description: API for the company-specific system server
  version: "1.0.0"
  title: System Server
  contact:
    email: sutdcaps13@gmail.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
tags:
  - name: developers

paths:
  /order/: # Note that this request is coming FROM the client app
    post:
      summary: client app submits a new delivery order to the system server
      operationId: submitOrder
      description: Adds a new order into the system server
      responses:
        '201':
          description: order created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
        '400':
          description: 'invalid input, object invalid'
        '409':
          description: an existing item already exists
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SubmitOrder'
        description: order id generated by the system

  /eject-robot/{request}:
    post:
      parameters:
        - in: path
          name: request
          required: true
          schema:
            $ref: '#/components/schemas/EjectRobot'
          description: data data for handling the ejected robot
      summary: handles the ejected outdoor robot from a building
      operationId: ejectRobot
      responses:
        '201':
          description: robot successfully ejected

components:
  schemas:
    Order:
      description: contains the order id and name of the delivery company
      type: object
      required:
        - id
        - company_name
      properties:
        id:
          type: string
          format: uuid
          example: d290f1ee-6c54-4b01-90e6-d701748f0851
        company_name:
          type: string
          example: barg delivery
        order_description:
          type : string
          example : "size 10"
    Address:
      type: object
      required:
        - building_name
        - unit
      properties:
        building_name:
          type: string
          example: Vivo City
        unit:
          type: string
          example: 'robots r us'
    Robot:
      type: object
      required:
        - id
      properties:
        id:
          type: string
          example: barg_external_robot_1121d
    EjectRobot:
      type: object
      required:
        - robot
        - egress_point
        - order
      properties:
        robot:
          $ref: '#/components/schemas/Robot'
        egress_point:
          $ref: '#/components/schemas/Address'
        order:
          $ref: '#/components/schemas/Order'
    SubmitOrder:
      type: object
      required:
        - order_details
        - customer_id
        - store_id
        - store_address
        - customer_address
      properties:
        order_details:
          type: string
          example: raspberry pi model 3B 4GB
        customer_id:
          type: string
          format: uuid
          example: d290f1ee-6c54-4b01-90e6-d701748f0851
        store_address:
          $ref: '#/components/schemas/Address'
        customer_address:
          $ref: '#/components/schemas/Address'